Hekaton/Hekaton/Controllers/GraphsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hekaton.Repositories.ActivityRepository;

namespace Hekaton.Controllers
{
    public class GraphsController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
    
}

Hekaton/Hekaton/Controllers/WorkoutPlanningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hekaton.Controllers
{
    public class WorkoutPlanningController : Controller
    {
        // GET: WorkoutPlanning
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hekaton/Hekaton/Views/Shared/Chat.cshtml
<div id="chat-window" style="position: fixed; width: 600px; height: 200px;right: 0%;bottom: 22%;margin-left: -300px;">
    <div class="box box-danger direct-chat direct-chat-danger">
        <div class="box-header with-border">
            <h3 class="box-title">Your personal chat with trainer!</h3>
            <div class="box-tools pull-right">
                <button id="close-button" class="btn btn-box-tool" style="background-color: #dd4b39;" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            <div id="conversaton-container" class="direct-chat-messages">
                <div id="admin-chat-part" class="direct-chat-msg">
                    <div class="direct-chat-info clearfix">
                        <span class="direct-chat-name pull-left">Alexander Pierce</span>
                        <span class="direct-chat-timestamp pull-right"> @DateTime.Now.ToString("HH:mm")</span>
                    </div>
                    <img class="direct-chat-img" src="http://www.freeiconspng.com/uploads/gym-icon-png-kansas-city-5.png" alt="message user image">
                    <div class="direct-chat-text">
                        Hello.How can I help You, Sir?
                    </div>
                </div>            
            </div>
            
            <div class="direct-chat-contacts">
                <ul class="contacts-list">
                    <li>
                        <a href="#">
                            <img class="contacts-list-img" src="../dist/img/user1-128x128.jpg" alt="Contact Avatar">
                            <div class="contacts-list-info">
                                <span class="contacts-list-name">
                                    Count Dracula
                                    <small class="contacts-list-date pull-right">2/28/2015</small>
                                </span>
                                <span class="contacts-list-msg">How have you been? I was...</span>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="box-footer">
            <div class="input-group">
                <input id="UserInput" onkeypress="runScript" type="text" name="message" placeholder="Type Message ..." class="form-control">
                <span class="input-group-btn">
                    <button id="SendButton" type="button" class="btn btn-danger btn-flat">Send</button>
                </span>
            </div>
        </div>
    </div>
</div>

Hekaton/Hekaton/Views/Shared/_AdminLteBreadcrumb.cshtml
@* 
 This breadcrumb partial is meant to be dropped into the top of the main content page
    and uses the AdminLte.Breadcrumb class to dynamically build the breadcrumb per page
*@

@if (ViewBag.Breadcrumb != null)
{
    <ol class="breadcrumb">
        @foreach (Crumb crumb in ViewBag.Breadcrumb)
        {
            <li>
                @if (crumb.HasLink)
                {
                    <a href="@crumb.Link">
                        @if (crumb.HasIcon)
                        {
                            <i class="fa @crumb.Icon"></i>
                        }

                        <span>@crumb.Text</span>
                    </a>
                }
                else
                {
                    if (crumb.HasIcon)
                    {
                        <i class="fa @crumb.Icon"></i>
                    }

                    <span>@crumb.Text</span>
                }
            </li>
        }
    </ol>
}

Hekaton/Hekaton/Views/Shared/_AdminLteLayout.cshtml
@* 
 This is the main dashboard layout that creates the AdminLTE look and feel
    It includes all of the relevant CSS and Js in this project and across CDNs around the web for optimal load times
    TODO: Use this layout in your views by either setting the "Layout" property 
    or changing your  _ViewStart.cshtml to use this layout
 *@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*TODO: Change App name*@
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    @*Source Sans Pro from Google Fonts*@
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" rel="stylesheet" />
    @*Bundle CSS, assuming includes Bootstrap CSS *@
    @Styles.Render("~/Content/css")
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/Scripts/AdminLTE/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/Content/AdminLTE/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    @*TODO: AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load.*@
    <link href="~/Content/AdminLTE/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="skin-blue">

    <div class="wrapper">

        @Html.Partial("_AdminLteTopMenu")
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_AdminLteLeftMenu")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.TitleSmall</small>
                </h1>
                @Html.Partial("_AdminLteBreadcrumb")
            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.0
            </div>
            <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>
    </div><!-- ./wrapper -->
    @* Bundles assume jquery 2.1.3 and Bootstrap 3 *@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- FastClick -->
    <script src='~/Scripts/AdminLTE/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="~/Scripts/AdminLTE/app.js" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="~/Scripts/AdminLTE/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="~/Scripts/AdminLTE/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="~/Scripts/AdminLTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="~/Scripts/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="~/Scripts/AdminLTE/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

Hekaton/Hekaton/Views/Shared/_AdminLteLeftMenu.cshtml
@* 
 This partial controls the left menu of the AdminLTE dashboard and is called automatically by _AdminLteLayout
    This is where you can add, modify, or remove navigation options in your app
    TODO: This preserves the links as-is for the demo, which lead to broken pages!
    It's up to you to make sure these links either get deleted or lead somewhere REAL!
*@


@{
    Layout = null;
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/Content/AdminLTE/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..." />
                <span class="input-group-btn">
                    <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-files-o"></i>
                    <span>Layout Options</span>
                    <span class="label label-primary pull-right">4</span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
                    <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
                    <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
                    <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/widgets.html">
                    <i class="fa fa-th"></i> <span>Widgets</span> <small class="label pull-right bg-green">new</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>UI Elements</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
                    <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
                    <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Forms</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
                    <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                    <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Tables</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/calendar.html">
                    <i class="fa fa-calendar"></i> <span>Calendar</span>
                    <small class="label pull-right bg-red">3</small>
                </a>
            </li>
            <li>
                <a href="pages/mailbox/mailbox.html">
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <small class="label pull-right bg-yellow">12</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Examples</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
                    <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
                    <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
                    <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Multilevel</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                    <li>
                        <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                            <li>
                                <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                </ul>
            </li>
            <li><a href="documentation/index.html"><i class="fa fa-book"></i> Documentation</a></li>
            <li class="header">LABELS</li>
            <li><a href="#"><i class="fa fa-circle-o text-danger"></i> Important</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-warning"></i> Warning</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-info"></i> Information</a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

Hekaton/Hekaton/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/ContentCSS")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="main-background">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="logo" href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="/Content/logo.png" title="title" alt="additional title" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                @if (@User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav" style="margin-left:50px">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle collapse" style="padding-left: 50px;" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Activities<span class="caret"></span></a>
                            <ul class="dropdown-menu" style="background-color: #101010; color: white;">
                                <li class="text_color">@Html.ActionLink("Record Activity", "LogActivity", "Home")</li>
                                <li class="text_color">@Html.ActionLink("Minimum Calorie Intake", "CalculatorCalories", "Home")</li>
                                <li class="text_color">@Html.ActionLink("Record Consumed Calorie", "CaloriesPerDay", "Home")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Workout Graphs", "Index", "Graphs")</li>
                        <li>@Html.ActionLink("Workout Planning", "Index", "WorkoutPlanning")</li>
                        <li>@Html.ActionLink("Events", "GetArticle", "Home")</li>
                        <li class="text_color">@Html.ActionLink("Nearest Gyms", "GetNearestGym", "Home")</li>
                        <li>
                                <span id="open-chat" class="glyphicon glyphicon-info-sign" aria-hidden="true" style="font-size: 30px; padding:8px"></span>
                        </li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @if(@User.Identity.IsAuthenticated){
        <div style="position: relative">
            @Html.Partial("Chat")
        </div>
        }
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.signalR-2.2.2.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/jquery.ui/jquery-ui.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
    <script src="http://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script src="~/Scripts/chat.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>